version = 1
[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

[update]
always = true
ignored_usernames = ["dependabot"]

[merge.message]
title = "pull_request_title"
body = "pull_request_body"